export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const SET_SHOW_FORM_REGISTER = 'SET_SHOW_FORM_REGISTER';
export const SET_SHOW_NOTIFICATION = 'SET_SHOW_NOTIFICATION';
export const SET_ALL_PROVINCE = 'SET_ALL_PROVINCE';
export const SET_SIGN_OUT = 'SET_SIGN_OUT';
export const SET_ARTICLE = 'SET_ARTICLE';
export const SET_ARTICLE_NOTE = 'SET_ARTICLE_NOTE';
export const SET_LOCATION = 'SET_LOCATION';